// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chunk_vertex_type::ChunkVertex;
use super::xz_coords_type::XzCoords;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chunk_vertex`.
///
/// Obtain a handle from the [`ChunkVertexTableAccess::chunk_vertex`] method on [`super::RemoteTables`],
/// like `ctx.db.chunk_vertex()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_vertex().on_insert(...)`.
pub struct ChunkVertexTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChunkVertex>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chunk_vertex`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChunkVertexTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChunkVertexTableHandle`], which mediates access to the table `chunk_vertex`.
    fn chunk_vertex(&self) -> ChunkVertexTableHandle<'_>;
}

impl ChunkVertexTableAccess for super::RemoteTables {
    fn chunk_vertex(&self) -> ChunkVertexTableHandle<'_> {
        ChunkVertexTableHandle {
            imp: self.imp.get_table::<ChunkVertex>("chunk_vertex"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChunkVertexInsertCallbackId(__sdk::CallbackId);
pub struct ChunkVertexDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ChunkVertexTableHandle<'ctx> {
    type Row = ChunkVertex;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkVertex> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChunkVertexInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkVertexInsertCallbackId {
        ChunkVertexInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkVertexInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChunkVertexDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkVertexDeleteCallbackId {
        ChunkVertexDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkVertexDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChunkVertex>("chunk_vertex");
}
pub struct ChunkVertexUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChunkVertexTableHandle<'ctx> {
    type UpdateCallbackId = ChunkVertexUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkVertexUpdateCallbackId {
        ChunkVertexUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkVertexUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ChunkVertex>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChunkVertex>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
