// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::xz_coords_type::XzCoords;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChunkVertex {
    pub grid: XzCoords,
    pub grid_x: i32,
    pub grid_z: i32,
    pub heightmap: Vec<f32>,
    pub vertices: Vec<f32>,
    pub normals: Vec<f32>,
}

impl __sdk::InModule for ChunkVertex {
    type Module = super::RemoteModule;
}
