// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::xz_coords_type::XzCoords;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OnChunkRequestedArgs {
    pub coord: XzCoords,
}

impl From<OnChunkRequestedArgs> for super::Reducer {
    fn from(args: OnChunkRequestedArgs) -> Self {
        Self::OnChunkRequested { coord: args.coord }
    }
}

impl __sdk::InModule for OnChunkRequestedArgs {
    type Module = super::RemoteModule;
}

pub struct OnChunkRequestedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `on_chunk_requested`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait on_chunk_requested {
    /// Request that the remote module invoke the reducer `on_chunk_requested` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_on_chunk_requested`] callbacks.
    fn on_chunk_requested(&self, coord: XzCoords) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `on_chunk_requested`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`OnChunkRequestedCallbackId`] can be passed to [`Self::remove_on_on_chunk_requested`]
    /// to cancel the callback.
    fn on_on_chunk_requested(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &XzCoords) + Send + 'static,
    ) -> OnChunkRequestedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_on_chunk_requested`],
    /// causing it not to run in the future.
    fn remove_on_on_chunk_requested(&self, callback: OnChunkRequestedCallbackId);
}

impl on_chunk_requested for super::RemoteReducers {
    fn on_chunk_requested(&self, coord: XzCoords) -> __sdk::Result<()> {
        self.imp
            .call_reducer("on_chunk_requested", OnChunkRequestedArgs { coord })
    }
    fn on_on_chunk_requested(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &XzCoords) + Send + 'static,
    ) -> OnChunkRequestedCallbackId {
        OnChunkRequestedCallbackId(self.imp.on_reducer(
            "on_chunk_requested",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::OnChunkRequested { coord },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, coord)
            }),
        ))
    }
    fn remove_on_on_chunk_requested(&self, callback: OnChunkRequestedCallbackId) {
        self.imp.remove_on_reducer("on_chunk_requested", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `on_chunk_requested`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_on_chunk_requested {
    /// Set the call-reducer flags for the reducer `on_chunk_requested` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn on_chunk_requested(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_on_chunk_requested for super::SetReducerFlags {
    fn on_chunk_requested(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("on_chunk_requested", flags);
    }
}
