// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::material_definition_type::MaterialDefinition;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OnMaterialDefinedArgs {
    pub e: MaterialDefinition,
}

impl From<OnMaterialDefinedArgs> for super::Reducer {
    fn from(args: OnMaterialDefinedArgs) -> Self {
        Self::OnMaterialDefined { e: args.e }
    }
}

impl __sdk::InModule for OnMaterialDefinedArgs {
    type Module = super::RemoteModule;
}

pub struct OnMaterialDefinedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `on_material_defined`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait on_material_defined {
    /// Request that the remote module invoke the reducer `on_material_defined` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_on_material_defined`] callbacks.
    fn on_material_defined(&self, e: MaterialDefinition) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `on_material_defined`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`OnMaterialDefinedCallbackId`] can be passed to [`Self::remove_on_on_material_defined`]
    /// to cancel the callback.
    fn on_on_material_defined(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &MaterialDefinition) + Send + 'static,
    ) -> OnMaterialDefinedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_on_material_defined`],
    /// causing it not to run in the future.
    fn remove_on_on_material_defined(&self, callback: OnMaterialDefinedCallbackId);
}

impl on_material_defined for super::RemoteReducers {
    fn on_material_defined(&self, e: MaterialDefinition) -> __sdk::Result<()> {
        self.imp
            .call_reducer("on_material_defined", OnMaterialDefinedArgs { e })
    }
    fn on_on_material_defined(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &MaterialDefinition) + Send + 'static,
    ) -> OnMaterialDefinedCallbackId {
        OnMaterialDefinedCallbackId(self.imp.on_reducer(
            "on_material_defined",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::OnMaterialDefined { e },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, e)
            }),
        ))
    }
    fn remove_on_on_material_defined(&self, callback: OnMaterialDefinedCallbackId) {
        self.imp
            .remove_on_reducer("on_material_defined", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `on_material_defined`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_on_material_defined {
    /// Set the call-reducer flags for the reducer `on_material_defined` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn on_material_defined(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_on_material_defined for super::SetReducerFlags {
    fn on_material_defined(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("on_material_defined", flags);
    }
}
