[package]
name = "game"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
spacetimedb-sdk = "1.1.1"
bevy = { version = "0.16", features = ["dynamic_linking"] }
bevy_ui = "0.16"
bevy_image = "0.16"
bevy_spacetimedb = "0.5.0"


# [build-dependencies]
# bevy-asset-loader = "0.16"
