[package]
name = "voxel-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
spacetimedb-sdk = "1.1.1"
futures = "0.3"
noise = "0.9"
nalgebra = "0.33"
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
image = "0.25"
colorgrad = "0.6" 
